### PR TITLE
Teach First Person and Arc Ball cameras to accept any up-axis

### LINKED ISSUE #122: Changing rotation (i.e. up-vector) of camera?
I cannot for the life of me figure out how to change the rotation of the camera. By rotation I mean rotation with respect to the direction the camera is pointing, i.e. changing the up vector, or, I think, the "roll" of the camera. Am I simply looking in the wrong places?

### PR DESCRIPTION
**Pull request by alvinhochun**
This adds `set_up_axis_dir` and changes `set_up_axis` to accept any up vector instead of limiting to only Y-up or Z-up. Still, only right-handed coordinate systems are supported.

In my previous PR #199 (which intended to fix #122), I limited the accepted up-axis directions to Y-axis and Z-axis only. However, it turns out I do have a use case for setting arbitrary up-axis (placing the camera on a tilted plane). This PR implements it for both the First Person and Arc Ball cameras.

(It turned out easier than I thought to implement.)

### CODE REVIEW

File: src/camera/arc_ball.rs [hunk 1]
```diff
@@ -439,18 +422,20 @@ impl Camera for ArcBall {
...
-impl CoordSystem {
+impl CoordSystemRh {
     #[inline]
-    fn up_axis(self) -> Vector3<f32> {
-        match self {
-            CoordSystem::RightHandYUp => Vector3::y(),
-            CoordSystem::RightHandZUp => Vector3::z(),
+    fn from_up_axis(up_axis: Unit<Vector3<f32>>) -> Self {
+        let rotation_to_y_up =
+            UnitQuaternion::rotation_between_axis(&up_axis, &Vector3::y_axis()).unwrap();
```
Comment (sebcrozet) [inline src/camera/arc_ball.rs:435]: The `unwrap` will panic if `up_axis` is set to `-Y`. So this should probably by something like `.or_else(|| UnitQuaternion::new(Vector3::x() * f32::PI))` (needs to be tested).

File: src/camera/first_person.rs [hunk 2]
```diff
@@ -458,18 +443,20 @@ fn check_optional_key_state(canvas: &Canvas, key: Option<Key>, key_state: Action
...
-impl CoordSystem {
+impl CoordSystemRh {
     #[inline]
-    fn up_axis(self) -> Vector3<f32> {
-        match self {
-            CoordSystem::RightHandYUp => Vector3::y(),
-            CoordSystem::RightHandZUp => Vector3::z(),
+    fn from_up_axis(up_axis: Unit<Vector3<f32>>) -> Self {
+        let rotation_to_y_up =
+            UnitQuaternion::rotation_between_axis(&up_axis, &Vector3::y_axis()).unwrap();
```
Comment (sebcrozet) [inline src/camera/first_person.rs:456]: Same remark as above.

File: src/camera/arc_ball.rs (hunk 1 above)
Comment (alvinhochun) [reply src/camera/arc_ball.rs]: Sorry, I messed this one up! Should be fixed.

**Comment by sebcrozet** [comment]
Great, thanks!
